PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>

SELECT ?repo ?do ?handle

FROM <https://archives.lib.umd.edu/>

WHERE {
  ?do a schema:MediaObject ;
      schema:sameAs ?handle ;
      schema:isPartOf ?repo .
}
